[package]
name = "mine_search"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mine_search"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
minecraft_protocol = { git = "https://github.com/kauri-off/minecraft_protocol.git" }
rand = "0.8.5"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
diesel = { version = "2.2.0", features = ["postgres", "chrono", "serde_json"] }
# build libpq and openssl as part of the build process
# uncomment these lines if you run into setup issues
pq-sys = { version = "0.6", features = ["bundled"] }
openssl-sys = { version = "0.9.100", features = ["vendored"] } 
chrono = "0.4.39"
colored = "2.2.0"
