[package]
name = "mc_lookup"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
minecraft_protocol = { git = "https://github.com/kauri-off/minecraft_protocol.git" }
rand = "0.8.5"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
