name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mine_search:$(date +%s)

    - name: Save docker image
      run: docker image save mine_search -o mine_search.tar.gz

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        path: mine_search.tar.gz
