name: Docker Image CI

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Worker image
        run: docker build -t ghcr.io/${{ github.repository }}/worker:latest -f worker.Dockerfile

      - name: Build Backend image
        run: docker build -t ghcr.io/${{ github.repository }}/backend:latest -f backend.Dockerfile

      - name: Push Worker image
        run: docker push ghcr.io/${{ github.repository }}/worker:latest

      - name: Push Backend image
        run: docker push ghcr.io/${{ github.repository }}/backend:latest
